import {
  Award,
  BadgeCheck,
  BrainCircuit,
  CalendarDays,
  Code2,
  Database,
  Download,
  ExternalLink,
  Github,
  Globe2,
  GraduationCap,
  Image,
  Instagram,
  Linkedin,
  Mail,
  MapPin,
  MonitorDot,
  Phone,
  ShieldCheck,
  Sparkles,
  Sprout,
  TerminalSquare,
  Twitter,
  Users,
  Workflow
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

import type { IconName } from "@/lib/site-data";

export const iconMap: Record<IconName, LucideIcon> = {
  adobe: Workflow,
  award: Award,
  badge: BadgeCheck,
  brain: BrainCircuit,
  calendar: CalendarDays,
  code: Code2,
  database: Database,
  download: Download,
  external: ExternalLink,
  farm: Sprout,
  github: Github,
  globe: Globe2,
  graduation: GraduationCap,
  hackerrank: TerminalSquare,
  image: Image,
  instagram: Instagram,
  linkedin: Linkedin,
  mail: Mail,
  map: MapPin,
  monitor: MonitorDot,
  phone: Phone,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: TerminalSquare,
  twitter: Twitter,
  users: Users
};
